# Generated by Django 4.2 on 2024-01-26 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_remove_transaction_reciever_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("failed", "failed"),
                    ("completed", "completed"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("request_sent", "request_sent"),
                    ("request_settled", "request settled"),
                    ("request_processing", "request processing"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("withdraw", "Withdraw"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("request", "Payment Request"),
                    ("none", "None"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=5,
                        max_length=20,
                        prefix="CARD",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("number", models.IntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("cvv", models.IntegerField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("master", "master"),
                            ("visa", "visa"),
                            ("verve", "verve"),
                        ],
                        default="master",
                        max_length=20,
                    ),
                ),
                ("card_status", models.BooleanField(default=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
